// this file is automatically generated by <?= basename(__FILE__) ?>

package main

import "regexp"

var	emojiRe = regexp.MustCompile(`:([^\s]+?):`)

var emoji = map[string]string{
<?php
$seen    = [];
$repeats = [];

foreach(file('emoji-test.txt') as $ln) {
    if($ln[0] === '#') continue;
    $ln = trim($ln);
    if($ln === '') continue;

    $ln    = substr($ln, strpos($ln, '#')+2);
    $emoji = substr($ln, 0, strpos($ln, ' '));
    $desc  = substr($ln, strpos($ln, ' ')+1);
    $desc = preg_replace("/^E\d+\.\d+\s/", "", $desc);
    // TRUE equality, I don't see color
    $desc = preg_replace('/: .+ skin tone.*/', '', $desc);

    // or families as groups of individuals
    if(strpos($desc, 'family') !== false) {
        $desc = 'family';
    }

    // or even the mf WORLD
    if(strpos($desc, 'globe') !== false) {
        $desc = 'globe';
    }

    // or “Japanese” “““buttons”””
    $desc = str_replace('Japanese “', '', $desc);
    $desc = str_replace('” button', '', $desc);

    // OR ANY OF THE FLAGS OF THE WORLD
    $desc = str_replace('flag: ', '', $desc);

    $desc = strtolower($desc);
    $desc = str_replace('’', '_', $desc);
    $desc = str_replace(' ', '_', $desc);
    $desc = str_replace('-', '_', $desc);

    if(in_array($desc, $seen)) {
        if(isset($repeats[$desc])) {
            $repeats[$desc][] = $emoji;
        } else {
            $repeats[$desc] = [$emoji];
        }
    } else {
        echo "\t\"$desc\": \"$emoji\",\n";
    }
    $seen[] = $desc;

    $before = $desc;

    // weasel words
    $desc = preg_replace('/_(face|monkey|hand|hands|back_of|gesture)$/', '', $desc);
    $desc = preg_replace('/_(face|facing)_/', '_', $desc);
    $desc = preg_replace('/^(hand_with|face_with|backhand_index|index|ear_with)_/', '', $desc);

    if($desc === $before) continue;

    if(in_array($desc, $seen)) {
        if(isset($repeats[$desc])) {
            $repeats[$desc][] = $emoji;
        } else {
            $repeats[$desc] = [$emoji];
        }
    } else {
        echo "\t\"$desc\": \"$emoji\",\n";
    }
    $seen[] = $desc;

}
?>
}

var other = map[string][]string{
<?php
foreach($repeats as $word => $emojis) {
    echo "\t\"$word\": []string{\"", implode('","', $emojis), "\"},\n";
}
?>
}

var jmote = map[string][]string{
<?php

function sanitize($name) {
    return preg_replace('/[^\w\+]+/', '_', trim(strtolower($name)));
}

$d = dir('emot');
while(($f = $d->read())!==false) {
    if(is_dir($f) || !preg_match('/^(\w+)\.txt$/', $f, $m)) continue;
    echo '"', sanitize($m[1]), '": []string{"', implode('","', array_map('trim', file("emot/$f"))), '"},', "\n";
}
?>
}
